/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwm;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Color;
import static java.lang.System.out;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author Egidius Mysliwietz
 */
public class Auswahl extends javax.swing.JFrame {

    String frage = "Sortieren Sie die Teilbefehle in der richtigen Reihenfolge!";
    ArrayList<String> userInput = new ArrayList();
    String[] choices = {"[column]", "[table]", "select", "from"};
    ArrayList<String> solution = new ArrayList();
    Date start, end;
    /**
     * Creates new form Auswahl
     */
    public Auswahl() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Background Stuff");
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(d.width, d.height);
        this.setVisible(true);
        //this.setAlwaysOnTop(true);
        labello.setBounds(0, 0, d.width, d.height);
        askandyeshallrecieve();
        solution.add("c"); solution.add("a"); solution.add("d"); solution.add("b");
        start = new Date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a_d = new javax.swing.JTextPane();
        a_c = new javax.swing.JTextPane();
        a_b = new javax.swing.JTextPane();
        a_a = new javax.swing.JTextPane();
        d = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        question = new javax.swing.JTextPane();
        labello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a_d.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        a_d.setToolTipText("");
        a_d.setFocusable(false);
        a_d.setOpaque(false);
        a_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_dMouseClicked(evt);
            }
        });
        getContentPane().add(a_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 630, 630, 40));

        a_c.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        a_c.setFocusable(false);
        a_c.setOpaque(false);
        a_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_cMouseClicked(evt);
            }
        });
        getContentPane().add(a_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 730, 630, 40));

        a_b.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        a_b.setFocusable(false);
        a_b.setOpaque(false);
        a_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_bMouseClicked(evt);
            }
        });
        getContentPane().add(a_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 830, 630, 40));

        a_a.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        a_a.setFocusable(false);
        a_a.setOpaque(false);
        a_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_aMouseClicked(evt);
            }
        });
        getContentPane().add(a_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 930, 660, 40));

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_d.png"))); // NOI18N
        d.setToolTipText("");
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
        });
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 610, -1, -1));

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_a.png"))); // NOI18N
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 901, -1, -1));

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_b.png"))); // NOI18N
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 805, -1, -1));

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_c.png"))); // NOI18N
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 708, -1, -1));

        question.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        question.setFocusable(false);
        question.setOpaque(false);
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, 630, 490));

        labello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/auwahlrunde-wwm.jpg"))); // NOI18N
        getContentPane().add(labello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int sel = 0;
    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_d.png")));
        if (!userInput.contains("d")) {
            userInput.add("d");  
            sel++;
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_dMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_c.png")));
        if (!userInput.contains("c")) {
           userInput.add("c");
           sel++;
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_cMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_b.png")));
        if (!userInput.contains("b")) {
            sel++;
            userInput.add("b");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_bMouseClicked

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_a.png")));
        if (!userInput.contains("a")) {
            sel++;
            userInput.add("a");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_aMouseClicked

    private void a_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_dMouseClicked
        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_d.png")));
        if (!userInput.contains("d")) {
            sel++;
            userInput.add("d");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_a_dMouseClicked

    private void a_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_cMouseClicked
        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_c.png")));
        if (!userInput.contains("c")) {
            sel++;
            userInput.add("c");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_a_cMouseClicked

    private void a_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_bMouseClicked
        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_b.png")));
        if (!userInput.contains("b")) {
            sel++;
            userInput.add("b");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_a_bMouseClicked

    private void a_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_aMouseClicked
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/selected_a.png")));
        if (!userInput.contains("a")) {
            sel++;
            userInput.add("a");
        }
        if(sel == 4) auswerten();
    }//GEN-LAST:event_a_aMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel a;
    public javax.swing.JTextPane a_a;
    public javax.swing.JTextPane a_b;
    public javax.swing.JTextPane a_c;
    public javax.swing.JTextPane a_d;
    public javax.swing.JLabel b;
    public javax.swing.JLabel c;
    public javax.swing.JLabel d;
    public javax.swing.JLabel labello;
    public javax.swing.JTextPane question;
    // End of variables declaration//GEN-END:variables

    private void askandyeshallrecieve() {
        V.u.appendToPane(question, frage, Color.lightGray, "Arial");
        V.u.appendToPane(a_a, choices[0], Color.lightGray, "Arial");
        V.u.appendToPane(a_b, choices[1], Color.lightGray, "Arial");
        V.u.appendToPane(a_c, choices[2], Color.lightGray, "Arial");
        V.u.appendToPane(a_d, choices[3], Color.lightGray, "Arial");
        a.setIcon(null);
        b.setIcon(null);
        c.setIcon(null);
        d.setIcon(null);
    }

    private void auswerten() {
        end = new Date();
        V.timeAuswahl = end.getTime() - start.getTime();
        
        question.setText("");
        a_a.setText("");
        a_b.setText("");
        a_c.setText("");
        a_d.setText("");
        V.u.appendToPane(question, "Korrekte Antwort:", Color.lightGray, "Arial");
        V.u.appendToPane(a_a, choices[1], Color.lightGray, "Arial");
        V.u.appendToPane(a_b, choices[3], Color.lightGray, "Arial");
        V.u.appendToPane(a_c, choices[0], Color.lightGray, "Arial");
        V.u.appendToPane(a_d, choices[2], Color.lightGray, "Arial");
        new Solution(userInput.equals(solution));
    }
}
