/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwm;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Egidius Mysliwietz
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Players
     */
    public Menu() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Menu");
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(d.width, d.height);
        this.setVisible(true);
        //this.setAlwaysOnTop(true);
        V.u.centerWindow(this);
        labello.setBounds(0, 0, d.width, d.height);
        marked_a.setIcon(null);
        marked_b.setIcon(null);
        marked_c.setIcon(null);
        marked_d.setIcon(null);
        V.u.loopSound("Intro-Sound");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marked_d = new javax.swing.JLabel();
        marked_c = new javax.swing.JLabel();
        marked_b = new javax.swing.JLabel();
        marked_a = new javax.swing.JLabel();
        labello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marked_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/DMarked.png"))); // NOI18N
        marked_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marked_dMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marked_dMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marked_dMouseExited(evt);
            }
        });
        getContentPane().add(marked_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 916, 880, 70));

        marked_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/CMarked.png"))); // NOI18N
        marked_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marked_cMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marked_cMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marked_cMouseExited(evt);
            }
        });
        getContentPane().add(marked_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 915, 880, 70));

        marked_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/BMarked.png"))); // NOI18N
        marked_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marked_bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marked_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marked_bMouseExited(evt);
            }
        });
        getContentPane().add(marked_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 825, 880, 70));

        marked_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/AMarked.png"))); // NOI18N
        marked_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marked_aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marked_aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marked_aMouseExited(evt);
            }
        });
        getContentPane().add(marked_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 828, 880, 70));

        labello.setFont(new java.awt.Font("Papyrus", 1, 48)); // NOI18N
        labello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/menu.png"))); // NOI18N
        getContentPane().add(labello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marked_aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_aMouseEntered
        marked_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/AMarked.png")));
    }//GEN-LAST:event_marked_aMouseEntered

    private void marked_aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_aMouseExited
        marked_a.setIcon(null);
    }//GEN-LAST:event_marked_aMouseExited

    private void marked_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_bMouseEntered
        marked_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/BMarked.png")));
    }//GEN-LAST:event_marked_bMouseEntered

    private void marked_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_bMouseExited
        marked_b.setIcon(null);
    }//GEN-LAST:event_marked_bMouseExited

    private void marked_cMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_cMouseEntered
        marked_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/CMarked.png")));
    }//GEN-LAST:event_marked_cMouseEntered

    private void marked_cMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_cMouseExited
        marked_c.setIcon(null);
    }//GEN-LAST:event_marked_cMouseExited

    private void marked_dMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_dMouseExited
        marked_d.setIcon(null);
    }//GEN-LAST:event_marked_dMouseExited

    private void marked_dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_dMouseEntered
        marked_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/menu/DMarked.png")));
    }//GEN-LAST:event_marked_dMouseEntered

    private void marked_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_bMouseClicked
        System.exit(0);
    }//GEN-LAST:event_marked_bMouseClicked

    private void marked_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_cMouseClicked
        JOptionPane.showMessageDialog(null, "Multiplayer not supported yet!\nGo pester Dr. Pardella about not explaining Server-Stuff");
    }//GEN-LAST:event_marked_cMouseClicked

    private void marked_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_dMouseClicked
        V.u.wip();
    }//GEN-LAST:event_marked_dMouseClicked

    private void marked_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marked_aMouseClicked
        new Players();
        dispose();
    }//GEN-LAST:event_marked_aMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel labello;
    public javax.swing.JLabel marked_a;
    public javax.swing.JLabel marked_b;
    public javax.swing.JLabel marked_c;
    public javax.swing.JLabel marked_d;
    // End of variables declaration//GEN-END:variables
}
