/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.System.err;
import static java.lang.System.out;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Egidius Mysliwietz
 */
public class Solution extends javax.swing.JFrame {

    boolean correct;
    Timer timer = new Timer();
    /**
     * Creates new form Solution
     */
    public Solution(boolean correct) {
        this.correct = correct;
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Background Stuff");
        setBackground(new Color(0, 0, 0, 0));
        this.setVisible(true);
        this.setAlwaysOnTop(true);
        util.Util.centerWindow(this);
        this.setAlwaysOnTop(true);
        t1.setText(V.playername);
        t2.setText(V.players.get(0));
        t3.setText(V.players.get(1));
        t4.setText(V.players.get(2));
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        win();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c2 = new javax.swing.JTextPane();
        c3 = new javax.swing.JTextPane();
        c1 = new javax.swing.JTextPane();
        c4 = new javax.swing.JTextPane();
        t1 = new javax.swing.JTextPane();
        t2 = new javax.swing.JTextPane();
        t3 = new javax.swing.JTextPane();
        t4 = new javax.swing.JTextPane();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c2.setEditable(false);
        c2.setBackground(new java.awt.Color(0, 0, 0));
        c2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        c2.setToolTipText("");
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 160, 40));

        c3.setEditable(false);
        c3.setBackground(new java.awt.Color(0, 0, 0));
        c3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        c3.setToolTipText("");
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 160, 40));

        c1.setEditable(false);
        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        c1.setToolTipText("");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 160, 40));

        c4.setEditable(false);
        c4.setBackground(new java.awt.Color(0, 0, 0));
        c4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        c4.setToolTipText("");
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 160, 40));

        t1.setEditable(false);
        t1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        t1.setToolTipText("");
        t1.setOpaque(false);
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 600, 40));

        t2.setEditable(false);
        t2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        t2.setToolTipText("");
        t2.setOpaque(false);
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 570, 40));

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        t3.setToolTipText("");
        t3.setOpaque(false);
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 620, 40));

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        t4.setToolTipText("");
        t4.setOpaque(false);
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 630, 40));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/strip.png"))); // NOI18N
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 470, -1, -1));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/strip.png"))); // NOI18N
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 360, -1, -1));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/strip.png"))); // NOI18N
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 250, -1, -1));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/strip.png"))); // NOI18N
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 72)); // NOI18N
        jLabel2.setText("Winner");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/auswahl/screen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane c1;
    public javax.swing.JTextPane c2;
    public javax.swing.JTextPane c3;
    public javax.swing.JTextPane c4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel p1;
    public javax.swing.JLabel p2;
    public javax.swing.JLabel p3;
    public javax.swing.JLabel p4;
    public javax.swing.JTextPane t1;
    public javax.swing.JTextPane t2;
    public javax.swing.JTextPane t3;
    public javax.swing.JTextPane t4;
    // End of variables declaration//GEN-END:variables

    private void win() { 
        c1.setText(V.u.convertTimeFromMilSecsToReadable(V.timeAuswahl));
        Random r = new Random();
        float f = r.nextFloat();
        if (!correct) {
           end_loose();
        } else {
           if(f > 0.9) {
               end_loose();
           } else {
               end_win();
           }
        }
    }
    
    void end_win() {
        jLabel2.setText("You Won");
        Random r = new Random();
        c2.setText(V.u.convertTimeFromMilSecsToReadable(V.timeAuswahl + r.nextInt(10000)));
        c3.setText(V.u.convertTimeFromMilSecsToReadable(V.timeAuswahl + r.nextInt(10000)));
        c4.setText(V.u.convertTimeFromMilSecsToReadable(V.timeAuswahl + r.nextInt(10000)));
        timer.scheduleAtFixedRate(new TimerTask() {
            int runs;
            @Override
            public void run() {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        p1.setVisible(!p1.isVisible());
                        runs++;
                        if (runs == 20) {
                            timer.cancel();
                            next();
                        }
                    }
                });
            }
        }, 0, 1000l / 10l); // 10 frames per second 
    }
    
    void end_loose() {
        JLabel j;
        JTextPane c;
        Random r = new Random();
        switch(r.nextInt(3)) {
            case 0: j = p4; c = c4; break;
            case 1: j = p3; c = c3; break;
            default: j = p2; c = c2;
        }
        c2.setText(V.u.convertTimeFromMilSecsToReadable(Math.abs(V.timeAuswahl - r.nextInt(10000))));
        c3.setText(V.u.convertTimeFromMilSecsToReadable(Math.abs(V.timeAuswahl - r.nextInt(10000))));
        c4.setText(V.u.convertTimeFromMilSecsToReadable(Math.abs(V.timeAuswahl - r.nextInt(10000))));
        Long l = Math.abs(V.timeAuswahl - r.nextInt(10000));
        while (l > V.timeAuswahl) {
            l = Math.abs(V.timeAuswahl - r.nextInt(10000));
        }
        c.setText(V.u.convertTimeFromMilSecsToReadable(l));
        jLabel2.setText("You Lost");
            timer.scheduleAtFixedRate(new TimerTask() {
            int runs;
            @Override
            public void run() {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        j.setVisible(!j.isVisible());
                        runs++;
                        if (runs == 10) {
                            timer.cancel();
                            System.exit(0);
                        }
                    }
                });
            }
        }, 0, 1000l / 10l); // 10 frames per second 
    }
    
    void next() {
        new Studio();
        dispose();
    }
}
